CORS object to support web servers
bufbuild/connect-go pull request #530
Opened 2023-06-26 09:40 UTC by emcfarlane

Adds a new method CORSDefault which returns a CORS object to help setup CORS with Connect and supported protocol headers.

Supports https://github.com/bufbuild/connect-go/issues/499

2023-06-28 16:55 UTC, akshayjshah requested changes
I like the shape of this PR, but really want it to live in the new Github org in a separate package. CORS isn't a super-common concern in Go, and this functionality doesn't depend on anything except a few string constants. Let's try to keep the main Connect package as lean as possible so it's not utterly unmanageable in 5y.

2023-06-28 16:55 UTC, akshayjshah commented on cors.go
> +			connectStreamingHeaderAcceptCompression, // Unused in web browsers, but added for future-proofing
The streaming headers aren't used by web browsers, but the unary headers absolutely are :)

2023-06-28 16:55 UTC, akshayjshah commented on cors.go
> +			grpcHeaderMessageType,                   // Unused in web browsers, but added for future-proofing
This header is weird. It's part of the gRPC protocol specification, but it seems to be unused _everywhere_ - nothing web-specific. I'd document it like so: "unused in practice, but part of gRPC protocol"

2023-06-28 16:55 UTC, akshayjshah commented on cors.go
> +			grpcHeaderDetails,                 // Error details in gRPC, gRPC-web
In general, I'd remove references to gRPC from the comments and focus on gRPC-Web. CORS is only relevant for browser support, and gRPC is unusable from browsers.

2023-06-28 16:55 UTC, akshayjshah commented on cors.go
> +func CORSDefault() CORS {
Think this'll fit better with the rest of the package as `func NewDefaultCORS` or `func NewCORSDefault`.

2023-06-28 16:55 UTC, akshayjshah commented on cors.go
> +// CORS config to help implement Cross-Origin Resource Sharing (CORS) header support.
Can we integrate this a little more closely with the HTML docs? Maybe we should include a link to the docs right now, and plan to update the docs to use this code once it's included in a release.

2023-06-29 14:26 UTC, emcfarlane commented
Closing, will reopen as a separate package.

2023-06-29 14:26 UTC, closed without merging